name: tombutton
description: A customizable button UI package for Flutter.
version: 0.0.4
homepage: https://pub.dev/packages/tombutton/versions/

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

# Pastikan menambahkan changelog ini agar bisa dipakai dengan benar
changelog:
  file: CHANGELOG.md
